# Generated by Django 5.1.3 on 2024-11-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
