# Generated by Django 5.1.2 on 2024-10-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('shop_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rating_default', models.DecimalField(decimal_places=1, max_digits=5)),
                ('food_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
