# Generated by Django 5.1.2 on 2024-10-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_makanan_delete_productentry_delete_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]

# Generated by Django 5.1.2 on 2024-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_makanan_delete_productentry_delete_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
