# Generated by Django 5.1 on 2024-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_makanan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
