# Generated by Django 5.1 on 2024-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userprofile_nama_remove_userprofile_nomor_hp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='image',
        ),
        migrations.AddField(
            model_name='makanan',
            name='jumlah_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='makanan',
            name='new_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
