# Generated by Django 5.1 on 2024-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_makanan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='jumlah_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='makanan',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
