# Generated by Django 5.1 on 2024-10-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_makanan_jumlah_review_makanan_total_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='total_rating',
        ),
    ]
