# Generated by Django 5.1 on 2024-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_makanan_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='rating_original',
            field=models.FloatField(default=0.0),
        ),
    ]
