# Generated by Django 5.1 on 2024-10-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_makanan_rating_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makanan',
            old_name='rating_original',
            new_name='new_rating',
        ),
    ]
