# Generated by Django 5.1 on 2024-10-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_rating_original_makanan_new_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='rating_default',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
