# Generated by Django 5.1 on 2024-10-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_makanan_rating_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='new_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
