# Generated by Django 5.1 on 2024-10-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_makanan_new_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='new_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
