# Generated by Django 5.1.2 on 2024-10-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_favorite_delete_favoriteproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='added_at',
        ),
        migrations.AddField(
            model_name='favorite',
            name='is_top_three',
            field=models.BooleanField(default=False),
        ),
    ]
