# Generated by Django 5.1.2 on 2024-10-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_remove_favorite_added_at_favorite_is_top_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
