# Generated by Django 5.1.2 on 2024-10-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0005_komentar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Komentar',
        ),
    ]
